---
- name: Apply Steam Machine configs
  hosts: bazzite
  pre_tasks:
    - name: "Install Decky Loader"
      ansible.builtin.import_tasks: ./tasks/install_decky_loader.yml
  roles:
    - unifideck

- name: Apply BC-250 specific configs
  hosts: bc250
  tasks:
    - name: "Disable Handheld Daemon"
      ansible.builtin.import_tasks: ./tasks/disable_hhd.yml
    - name: "Disable sleep and hibernation"
      ansible.builtin.import_tasks: ./tasks/disable_sleep.yml
  roles:
    - cyan_skillfish
    - cpu_undervolt
    - wifi_persistence
