---
- name: "Mask sleep and suspend targets"
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: true
    state: stopped
  loop:
    - sleep.target
    - suspend.target
    - hybrid-sleep.target
