- name: Ensure decky plugin directory exists
  become: true
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/homebrew/plugins"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Fetch metadata
  block:
    - name: Check latest Unifideck release
      ansible.builtin.uri:
        url: https://api.github.com/repos/mubaraknumann/unifideck/releases/latest
        return_content: true
      register: unifideck_release

    - name: Check existing Unifideck version
      ansible.builtin.slurp:
        src: "{{ unifideck_plugin_path }}/package.json"
      register: unifideck_existing_package
      ignore_errors: true

    - name: Set version facts
      ansible.builtin.set_fact:
        unifideck_zip_url: "{{ unifideck_release.json.assets.0.browser_download_url }}"
        unifideck_latest_ver: "{{ unifideck_release.json.tag_name | replace('Release-', '') }}"
        unifideck_current_ver: "{{ (unifideck_existing_package.content | b64decode | from_json).version | default('0.0.0') }}"

- name: Update/Install Unifideck plugin
  when: unifideck_latest_ver is ansible.builtin.version(unifideck_current_ver, '>')
  become: true
  block:
    - name: Downloading Unifideck plugin
      ansible.builtin.unarchive:
        src: "{{ unifideck_zip_url }}"
        dest: "{{ unifideck_homebrew_path }}"
        remote_src: true
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "u=rwX,g=rX,o=rX"

    - name: Update plugin permissions
      become: true
      ansible.builtin.file:
        path: "{{ unifideck_plugin_path }}/plugin.json"
        owner: root
        group: root
        mode: '0644'

    - name: Restart Decky Loader
      become: true
      ansible.builtin.systemd_service:
        name: plugin_loader
        state: restarted
